### ISSUE TITLE
Tests have started to fail with MIME-Types-2.23

### ISSUE THREAD

**Issue by andk** [oalders/archive-any#11]
A pair of a pass and a fail report with the same perl, with difference being only the version of MIME::Types:

http://www.cpantesters.org/cpan/report/a7caf5dc-868b-11ed-a952-0c1da2a01845

http://www.cpantesters.org/cpan/report/f915532e-868b-11ed-bc06-6d20a2a01845

@markov2, do you want to chime in?

Greetings,

**Comment by markov2** [comment]
Gentoo officially registered the use of 'tar' and 'tbz2' extensions, where they were always defined informally as 'application/x-tar' and 'application/x-gtar'.  Another example where reality breaks standardization processes.

Added to the list of exceptions.  Released as MIME::Types 2.24

**Comment by andk** [comment]
Thanks, with that release Archive-Any gives a PASS again: http://www.cpantesters.org/cpan/report/539b371c-86c0-11ed-a186-bd3c5ba887d6

**Comment by oalders** [comment]
Thanks @andk and @markov2!
