### ISSUE TITLE
[PATCH] Declare @ISA before using it

### ISSUE THREAD

**Issue by real-dam** [oalders/archive-any#3]
Hi,

While preparing the upgrade of Archive-Any in Debian, I encountered an error in
the automated package testing. Part of it checks the syntax of all modules and
Archive::Any::Tar and Archive::Any::Zip fail because @ISA is used without
declaration in 'use strict' scope.

The patch at [1] fixes the problem (and adds both modules to t/00compile.t), but
I wonder if these modules are to be used at all.

[1] https://anonscm.debian.org/cgit/pkg-perl/packages/libarchive-any-perl.git/plain/debian/patches/our-ISA.patch

Thanks for considering,
  Damyan Ivanov,
  Debian Perl Group

**Comment by oalders** [comment]
@real-dam sorry, somehow I missed this.  Thanks very much for your contribution.  It has been merged.

**Comment by carnil** [comment]
Hi

The change has been made for Archive::Any::Tar but not for Archive::Any::Zip, was this on purpose? In Debian we still will need to patch the later one to pass the automated syntax checks.

Regards,
Salvatore

**Comment by oalders** [comment]
Hi Salvatore,

It was not intentional.  I've just released a fixed version to CPAN.  Should be available shortly.

Best,

Olaf
